# specify the node base image with your desired version node:<version>
FROM cgr.dev/chainguard/node:latest

ENV NODE_ENV=production

WORKDIR /app

COPY --chown=node:node ["package.json", "server.js", "./"]

CMD [ "server.js" ]